### ISSUE TITLE
igev_stereo_ddim confusion

### ISSUE THREAD

**Issue by xubin1994** [iSEE-Laboratory/DiffuVolume#1]
It seems that the input parameters of the ddim_sample of igev_stereo_ddim do not match the actual call

**Comment by zhengdian1** [comment]
What do you mean "do not match the actual call"

**Comment by xubin1994** [comment]
> What do you mean "do not match the actual call"

ddim_sample function definition and actual calls, the number of parameters is different
https://github.com/iSEE-Laboratory/DiffuVolume/blob/9e0473f47e553f7cc1d80aa886659de4383a30b7/KITTI15_IGEV/core/igev_stereo_ddim.py#L421
https://github.com/iSEE-Laboratory/DiffuVolume/blob/a44e611d8013eb8837dd31dd7be3714bbee3011b/KITTI15/core/igev_stereo_ddim.py#L293

**Comment by zhengdian1** [comment]
Thanks for the heads up. We have updated the code and you can successfully run it now.

**Comment by xubin1994** [comment]
If the parameters here are (disp, Disp),  
https://github.com/iSEE-Laboratory/DiffuVolume/blob/6789b6df2228bfd145b0c8d00789497ba247af16/KITTI15/core/igev_stereo_ddim.py#L425


Then the initial output of the flow of model_predition will be 0. There should be a problem here
https://github.com/iSEE-Laboratory/DiffuVolume/blob/6789b6df2228bfd145b0c8d00789497ba247af16/KITTI15/core/igev_stereo_ddim.py#L238

**Comment by zhengdian1** [comment]
Please read our code seriously, what you say will not happen as Line 234 reinitializes the coords1
Try the code.
